# Generated by Django 5.2.5 on 2025-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
